//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_App_SistemKontroloru.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banned_App
    {
        public int id { get; set; }
        public string Hardware_Id { get; set; }
        public string P_Name { get; set; }
        public string Title_ { get; set; }
        public Nullable<System.DateTime> Datetime_ { get; set; }
    }
}
