//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_App_SistemKontroloru.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PC_Running_Apps
    {
        public int @int { get; set; }
        public string Hardware_id { get; set; }
        public string Name_ { get; set; }
        public string Title_ { get; set; }
    }
}
