//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_App_SistemKontroloru.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class System_Usage
    {
        public int id { get; set; }
        public string Hardware_Id { get; set; }
        public Nullable<double> Cpu { get; set; }
        public Nullable<double> Memory { get; set; }
        public Nullable<double> Network_Rec { get; set; }
        public Nullable<double> Network_Out { get; set; }
        public Nullable<double> IO_Read { get; set; }
        public Nullable<double> IO_Write { get; set; }
        public Nullable<System.DateTime> Datetime_ { get; set; }
        public Nullable<bool> Sync { get; set; }
    }
}
