//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_App_SistemKontroloru.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class admin_WebApp_DatabaseEntities : DbContext
    {
        public admin_WebApp_DatabaseEntities()
            : base("name=admin_WebApp_DatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PC_Running_Apps> PC_Running_Apps { get; set; }
        public virtual DbSet<Screen_Capture> Screen_Capture { get; set; }
        public virtual DbSet<Screen_Record> Screen_Record { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User_Details> User_Details { get; set; }
        public virtual DbSet<Browser_Histories> Browser_Histories { get; set; }
        public virtual DbSet<Banned_App> Banned_App { get; set; }
        public virtual DbSet<PC_App_Locations> PC_App_Locations { get; set; }
        public virtual DbSet<cmd_output_> cmd_output_ { get; set; }
        public virtual DbSet<System_Usage> System_Usage { get; set; }
        public virtual DbSet<App_Usage> App_Usage { get; set; }
        public virtual DbSet<PC_Details> PC_Details { get; set; }
        public virtual DbSet<Work_Order> Work_Order { get; set; }
    }
}
