//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_App_SistemKontroloru.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Work_Order
    {
        public int id { get; set; }
        public string Hardware_Id { get; set; }
        public string Work_ { get; set; }
        public string Query_ { get; set; }
        public Nullable<int> Temp_ { get; set; }
        public Nullable<bool> Result_ { get; set; }
        public Nullable<bool> Active_ { get; set; }
        public Nullable<System.DateTime> Datetime_ { get; set; }
    }
}
