//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemKontroloruDesktopApp.WCF_Servis {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Work_Order", Namespace="http://schemas.datacontract.org/2004/07/Web_App_SistemKontroloru.Models")]
    [System.SerializableAttribute()]
    public partial class Work_Order : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> Active_Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> Datetime_Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Hardware_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Query_Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> Result_Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Temp_Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Work_Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Active_ {
            get {
                return this.Active_Field;
            }
            set {
                if ((this.Active_Field.Equals(value) != true)) {
                    this.Active_Field = value;
                    this.RaisePropertyChanged("Active_");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Datetime_ {
            get {
                return this.Datetime_Field;
            }
            set {
                if ((this.Datetime_Field.Equals(value) != true)) {
                    this.Datetime_Field = value;
                    this.RaisePropertyChanged("Datetime_");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Hardware_Id {
            get {
                return this.Hardware_IdField;
            }
            set {
                if ((object.ReferenceEquals(this.Hardware_IdField, value) != true)) {
                    this.Hardware_IdField = value;
                    this.RaisePropertyChanged("Hardware_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Query_ {
            get {
                return this.Query_Field;
            }
            set {
                if ((object.ReferenceEquals(this.Query_Field, value) != true)) {
                    this.Query_Field = value;
                    this.RaisePropertyChanged("Query_");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Result_ {
            get {
                return this.Result_Field;
            }
            set {
                if ((this.Result_Field.Equals(value) != true)) {
                    this.Result_Field = value;
                    this.RaisePropertyChanged("Result_");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Temp_ {
            get {
                return this.Temp_Field;
            }
            set {
                if ((this.Temp_Field.Equals(value) != true)) {
                    this.Temp_Field = value;
                    this.RaisePropertyChanged("Temp_");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Work_ {
            get {
                return this.Work_Field;
            }
            set {
                if ((object.ReferenceEquals(this.Work_Field, value) != true)) {
                    this.Work_Field = value;
                    this.RaisePropertyChanged("Work_");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCF_Servis.ISistem_Kontroloru_Servis_01")]
    public interface ISistem_Kontroloru_Servis_01 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistem_Kontroloru_Servis_01/Servis_Kontrol", ReplyAction="http://tempuri.org/ISistem_Kontroloru_Servis_01/Servis_KontrolResponse")]
        bool Servis_Kontrol();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistem_Kontroloru_Servis_01/Servis_Kontrol", ReplyAction="http://tempuri.org/ISistem_Kontroloru_Servis_01/Servis_KontrolResponse")]
        System.Threading.Tasks.Task<bool> Servis_KontrolAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistem_Kontroloru_Servis_01/giris", ReplyAction="http://tempuri.org/ISistem_Kontroloru_Servis_01/girisResponse")]
        string giris(string username, string password, string Hardware_Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistem_Kontroloru_Servis_01/giris", ReplyAction="http://tempuri.org/ISistem_Kontroloru_Servis_01/girisResponse")]
        System.Threading.Tasks.Task<string> girisAsync(string username, string password, string Hardware_Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistem_Kontroloru_Servis_01/girisSonrasiKontrol", ReplyAction="http://tempuri.org/ISistem_Kontroloru_Servis_01/girisSonrasiKontrolResponse")]
        string girisSonrasiKontrol(string hardware_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistem_Kontroloru_Servis_01/girisSonrasiKontrol", ReplyAction="http://tempuri.org/ISistem_Kontroloru_Servis_01/girisSonrasiKontrolResponse")]
        System.Threading.Tasks.Task<string> girisSonrasiKontrolAsync(string hardware_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistem_Kontroloru_Servis_01/ayarKontrol", ReplyAction="http://tempuri.org/ISistem_Kontroloru_Servis_01/ayarKontrolResponse")]
        string ayarKontrol(string username, string password, string hardware_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistem_Kontroloru_Servis_01/ayarKontrol", ReplyAction="http://tempuri.org/ISistem_Kontroloru_Servis_01/ayarKontrolResponse")]
        System.Threading.Tasks.Task<string> ayarKontrolAsync(string username, string password, string hardware_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistem_Kontroloru_Servis_01/isEmri", ReplyAction="http://tempuri.org/ISistem_Kontroloru_Servis_01/isEmriResponse")]
        SistemKontroloruDesktopApp.WCF_Servis.Work_Order[] isEmri(string Hardware_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistem_Kontroloru_Servis_01/isEmri", ReplyAction="http://tempuri.org/ISistem_Kontroloru_Servis_01/isEmriResponse")]
        System.Threading.Tasks.Task<SistemKontroloruDesktopApp.WCF_Servis.Work_Order[]> isEmriAsync(string Hardware_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistem_Kontroloru_Servis_01/isEmri_Kapat", ReplyAction="http://tempuri.org/ISistem_Kontroloru_Servis_01/isEmri_KapatResponse")]
        string isEmri_Kapat(string Hardware_id, string isemri__, string yol, string cmd_output);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistem_Kontroloru_Servis_01/isEmri_Kapat", ReplyAction="http://tempuri.org/ISistem_Kontroloru_Servis_01/isEmri_KapatResponse")]
        System.Threading.Tasks.Task<string> isEmri_KapatAsync(string Hardware_id, string isemri__, string yol, string cmd_output);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistem_Kontroloru_Servis_01/uygulama_listesi_gonder", ReplyAction="http://tempuri.org/ISistem_Kontroloru_Servis_01/uygulama_listesi_gonderResponse")]
        string uygulama_listesi_gonder(string Hardware_id, System.Data.DataTable tablo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistem_Kontroloru_Servis_01/uygulama_listesi_gonder", ReplyAction="http://tempuri.org/ISistem_Kontroloru_Servis_01/uygulama_listesi_gonderResponse")]
        System.Threading.Tasks.Task<string> uygulama_listesi_gonderAsync(string Hardware_id, System.Data.DataTable tablo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistem_Kontroloru_Servis_01/calisan_uygulama_gonder", ReplyAction="http://tempuri.org/ISistem_Kontroloru_Servis_01/calisan_uygulama_gonderResponse")]
        string calisan_uygulama_gonder(string Hardware_id, System.Data.DataTable tablo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistem_Kontroloru_Servis_01/calisan_uygulama_gonder", ReplyAction="http://tempuri.org/ISistem_Kontroloru_Servis_01/calisan_uygulama_gonderResponse")]
        System.Threading.Tasks.Task<string> calisan_uygulama_gonderAsync(string Hardware_id, System.Data.DataTable tablo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistem_Kontroloru_Servis_01/genel_kullanim_gonder", ReplyAction="http://tempuri.org/ISistem_Kontroloru_Servis_01/genel_kullanim_gonderResponse")]
        string genel_kullanim_gonder(string Hardware_id, double cpu, double memory, double network_rec, double network_out, double io_rec, double io_out, System.DateTime datetime_);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistem_Kontroloru_Servis_01/genel_kullanim_gonder", ReplyAction="http://tempuri.org/ISistem_Kontroloru_Servis_01/genel_kullanim_gonderResponse")]
        System.Threading.Tasks.Task<string> genel_kullanim_gonderAsync(string Hardware_id, double cpu, double memory, double network_rec, double network_out, double io_rec, double io_out, System.DateTime datetime_);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistem_Kontroloru_Servis_01/uygulama_kullanim_gonder", ReplyAction="http://tempuri.org/ISistem_Kontroloru_Servis_01/uygulama_kullanim_gonderResponse")]
        string uygulama_kullanim_gonder(string Hardware_id, System.Data.DataTable app_list_table);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistem_Kontroloru_Servis_01/uygulama_kullanim_gonder", ReplyAction="http://tempuri.org/ISistem_Kontroloru_Servis_01/uygulama_kullanim_gonderResponse")]
        System.Threading.Tasks.Task<string> uygulama_kullanim_gonderAsync(string Hardware_id, System.Data.DataTable app_list_table);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistem_Kontroloru_Servis_01/pc_information", ReplyAction="http://tempuri.org/ISistem_Kontroloru_Servis_01/pc_informationResponse")]
        void pc_information(string hardwareid, string Domain_User_Name, string Version_, double Memory_Size_Gb, string Processor_Name, string Motherboard_Info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistem_Kontroloru_Servis_01/pc_information", ReplyAction="http://tempuri.org/ISistem_Kontroloru_Servis_01/pc_informationResponse")]
        System.Threading.Tasks.Task pc_informationAsync(string hardwareid, string Domain_User_Name, string Version_, double Memory_Size_Gb, string Processor_Name, string Motherboard_Info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistem_Kontroloru_Servis_01/kullanimlari_esitle", ReplyAction="http://tempuri.org/ISistem_Kontroloru_Servis_01/kullanimlari_esitleResponse")]
        void kullanimlari_esitle(string thardwareid, System.Data.DataTable sys_table, System.Data.DataTable app_table);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistem_Kontroloru_Servis_01/kullanimlari_esitle", ReplyAction="http://tempuri.org/ISistem_Kontroloru_Servis_01/kullanimlari_esitleResponse")]
        System.Threading.Tasks.Task kullanimlari_esitleAsync(string thardwareid, System.Data.DataTable sys_table, System.Data.DataTable app_table);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISistem_Kontroloru_Servis_01Channel : SistemKontroloruDesktopApp.WCF_Servis.ISistem_Kontroloru_Servis_01, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Sistem_Kontroloru_Servis_01Client : System.ServiceModel.ClientBase<SistemKontroloruDesktopApp.WCF_Servis.ISistem_Kontroloru_Servis_01>, SistemKontroloruDesktopApp.WCF_Servis.ISistem_Kontroloru_Servis_01 {
        
        public Sistem_Kontroloru_Servis_01Client() {
        }
        
        public Sistem_Kontroloru_Servis_01Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Sistem_Kontroloru_Servis_01Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Sistem_Kontroloru_Servis_01Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Sistem_Kontroloru_Servis_01Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Servis_Kontrol() {
            return base.Channel.Servis_Kontrol();
        }
        
        public System.Threading.Tasks.Task<bool> Servis_KontrolAsync() {
            return base.Channel.Servis_KontrolAsync();
        }
        
        public string giris(string username, string password, string Hardware_Id) {
            return base.Channel.giris(username, password, Hardware_Id);
        }
        
        public System.Threading.Tasks.Task<string> girisAsync(string username, string password, string Hardware_Id) {
            return base.Channel.girisAsync(username, password, Hardware_Id);
        }
        
        public string girisSonrasiKontrol(string hardware_id) {
            return base.Channel.girisSonrasiKontrol(hardware_id);
        }
        
        public System.Threading.Tasks.Task<string> girisSonrasiKontrolAsync(string hardware_id) {
            return base.Channel.girisSonrasiKontrolAsync(hardware_id);
        }
        
        public string ayarKontrol(string username, string password, string hardware_id) {
            return base.Channel.ayarKontrol(username, password, hardware_id);
        }
        
        public System.Threading.Tasks.Task<string> ayarKontrolAsync(string username, string password, string hardware_id) {
            return base.Channel.ayarKontrolAsync(username, password, hardware_id);
        }
        
        public SistemKontroloruDesktopApp.WCF_Servis.Work_Order[] isEmri(string Hardware_id) {
            return base.Channel.isEmri(Hardware_id);
        }
        
        public System.Threading.Tasks.Task<SistemKontroloruDesktopApp.WCF_Servis.Work_Order[]> isEmriAsync(string Hardware_id) {
            return base.Channel.isEmriAsync(Hardware_id);
        }
        
        public string isEmri_Kapat(string Hardware_id, string isemri__, string yol, string cmd_output) {
            return base.Channel.isEmri_Kapat(Hardware_id, isemri__, yol, cmd_output);
        }
        
        public System.Threading.Tasks.Task<string> isEmri_KapatAsync(string Hardware_id, string isemri__, string yol, string cmd_output) {
            return base.Channel.isEmri_KapatAsync(Hardware_id, isemri__, yol, cmd_output);
        }
        
        public string uygulama_listesi_gonder(string Hardware_id, System.Data.DataTable tablo) {
            return base.Channel.uygulama_listesi_gonder(Hardware_id, tablo);
        }
        
        public System.Threading.Tasks.Task<string> uygulama_listesi_gonderAsync(string Hardware_id, System.Data.DataTable tablo) {
            return base.Channel.uygulama_listesi_gonderAsync(Hardware_id, tablo);
        }
        
        public string calisan_uygulama_gonder(string Hardware_id, System.Data.DataTable tablo) {
            return base.Channel.calisan_uygulama_gonder(Hardware_id, tablo);
        }
        
        public System.Threading.Tasks.Task<string> calisan_uygulama_gonderAsync(string Hardware_id, System.Data.DataTable tablo) {
            return base.Channel.calisan_uygulama_gonderAsync(Hardware_id, tablo);
        }
        
        public string genel_kullanim_gonder(string Hardware_id, double cpu, double memory, double network_rec, double network_out, double io_rec, double io_out, System.DateTime datetime_) {
            return base.Channel.genel_kullanim_gonder(Hardware_id, cpu, memory, network_rec, network_out, io_rec, io_out, datetime_);
        }
        
        public System.Threading.Tasks.Task<string> genel_kullanim_gonderAsync(string Hardware_id, double cpu, double memory, double network_rec, double network_out, double io_rec, double io_out, System.DateTime datetime_) {
            return base.Channel.genel_kullanim_gonderAsync(Hardware_id, cpu, memory, network_rec, network_out, io_rec, io_out, datetime_);
        }
        
        public string uygulama_kullanim_gonder(string Hardware_id, System.Data.DataTable app_list_table) {
            return base.Channel.uygulama_kullanim_gonder(Hardware_id, app_list_table);
        }
        
        public System.Threading.Tasks.Task<string> uygulama_kullanim_gonderAsync(string Hardware_id, System.Data.DataTable app_list_table) {
            return base.Channel.uygulama_kullanim_gonderAsync(Hardware_id, app_list_table);
        }
        
        public void pc_information(string hardwareid, string Domain_User_Name, string Version_, double Memory_Size_Gb, string Processor_Name, string Motherboard_Info) {
            base.Channel.pc_information(hardwareid, Domain_User_Name, Version_, Memory_Size_Gb, Processor_Name, Motherboard_Info);
        }
        
        public System.Threading.Tasks.Task pc_informationAsync(string hardwareid, string Domain_User_Name, string Version_, double Memory_Size_Gb, string Processor_Name, string Motherboard_Info) {
            return base.Channel.pc_informationAsync(hardwareid, Domain_User_Name, Version_, Memory_Size_Gb, Processor_Name, Motherboard_Info);
        }
        
        public void kullanimlari_esitle(string thardwareid, System.Data.DataTable sys_table, System.Data.DataTable app_table) {
            base.Channel.kullanimlari_esitle(thardwareid, sys_table, app_table);
        }
        
        public System.Threading.Tasks.Task kullanimlari_esitleAsync(string thardwareid, System.Data.DataTable sys_table, System.Data.DataTable app_table) {
            return base.Channel.kullanimlari_esitleAsync(thardwareid, sys_table, app_table);
        }
    }
}
